In [15]:
import tensorflow as tf
from tensorflow import keras

In [34]:
x = tf.random.normal(shape=(3, 10))
print(x)

tf.Tensor(
[[-0.8140562   0.8031542  -1.0300479  -0.2602072  -1.6607195  -0.89462566
   1.3653389  -0.76598334  0.7951272  -0.59535027]
 [ 0.9027702  -0.98538995  0.4489626  -0.5381796   0.05176629 -0.84623504
  -0.05147726  0.06465504 -0.13427044  1.256677  ]
 [ 1.0203266  -1.1068016  -1.5425494  -0.38906413  0.6385947   0.5119138
  -0.11158727 -1.9757162  -0.11919313  0.09350387]], shape=(3, 10), dtype=float32)


In [35]:
#Initialize the translation weights
Wt_initial_value = tf.random.normal(x.shape)
wt = tf.Variable(Wt_initial_value)
print(wt)

<tf.Variable 'Variable:0' shape=(3, 10) dtype=float32, numpy=
array([[-0.16639055,  1.8621396 ,  1.5952841 , -0.02198732,  1.2010659 ,
         2.5265124 ,  0.56241196,  0.49810216,  0.51164734, -0.70859563],
       [ 0.2206368 ,  1.1500617 ,  0.01687999,  0.09464136,  1.8327093 ,
         0.08962391,  1.0405595 , -0.10094868,  1.7242155 ,  1.6143506 ],
       [-1.4703797 ,  0.25055054, -0.13980678, -0.027584  , -0.287042  ,
         0.23640494, -2.0323553 , -0.18664008, -0.03102536, -1.8995535 ]],
      dtype=float32)>


In [36]:
#Initialize the dilation weights
Wd_initial_value = tf.random.normal(x.shape)
wd = tf.Variable(Wd_initial_value)
print(wd)

<tf.Variable 'Variable:0' shape=(3, 10) dtype=float32, numpy=
array([[ 0.20195241,  0.4478894 ,  1.2505057 , -0.3262428 , -0.12398466,
        -0.43210876, -1.1440946 ,  0.17258835, -0.28988925,  1.4998627 ],
       [ 0.09308425,  0.9406076 ,  0.5447096 ,  1.3697822 , -0.5909966 ,
         0.00439011, -0.8456004 , -0.40787724, -0.42699522,  1.6847346 ],
       [ 1.136125  ,  1.37759   ,  2.2391949 , -1.069701  ,  1.0363955 ,
         0.48734328,  1.0430757 ,  0.0054862 ,  1.2267728 , -0.9123073 ]],
      dtype=float32)>


In [37]:
def z(x,wd,wt):
    a = tf.math.subtract(x,wt)
    return tf.math.divide(a,wd)

In [38]:
calc = z(x,wd,wt)
print(calc)

tf.Tensor(
[[-3.2070212e+00 -2.3643906e+00 -2.0994163e+00  7.3019201e-01
   2.3081770e+01  7.9173079e+00 -7.0180118e-01 -7.3242807e+00
  -9.7789025e-01  7.5503826e-02]
 [ 7.3281293e+00 -2.2702897e+00  7.9323477e-01 -4.6198654e-01
   3.0134573e+00 -2.1317435e+02  1.2914337e+00 -4.0601367e-01
   4.3524747e+00 -2.1230260e-01]
 [ 2.1922822e+00 -9.8530924e-01 -6.2644953e-01  3.3792633e-01
   8.9313066e-01  5.6532806e-01  1.8414465e+00 -3.2610480e+02
  -7.1869686e-02 -2.1846337e+00]], shape=(3, 10), dtype=float32)


In [41]:
z = tf.ones(x.shape)

In [43]:
for X, WD, WT in x, wd, wt:
    Z = tf.math.divide(tf.math.subtract(X, WT),WD)
    
print(Z)

tf.Tensor(
[ 5.9101162e+00  1.4013066e+00  1.0278983e+02  5.9135634e-02
  8.1197160e-01  2.5552418e+01  2.4936271e+00 -6.7830720e+00
  3.1473601e-01  7.3773187e-01], shape=(10,), dtype=float32)
